# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor

# Include any dependencies generated for this target.
include src/CMakeFiles/../ANYKA37EOS.dir/depend.make

# Include the progress variables for this target.
include src/CMakeFiles/../ANYKA37EOS.dir/progress.make

# Include the compile flags for this target's objects.
include src/CMakeFiles/../ANYKA37EOS.dir/flags.make

src/CMakeFiles/../ANYKA37EOS.dir/main.c.o: src/CMakeFiles/../ANYKA37EOS.dir/flags.make
src/CMakeFiles/../ANYKA37EOS.dir/main.c.o: src/main.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building C object src/CMakeFiles/../ANYKA37EOS.dir/main.c.o"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37EOS.dir/main.c.o   -c /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/main.c

src/CMakeFiles/../ANYKA37EOS.dir/main.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37EOS.dir/main.c.i"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/main.c > CMakeFiles/../ANYKA37EOS.dir/main.c.i

src/CMakeFiles/../ANYKA37EOS.dir/main.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37EOS.dir/main.c.s"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/main.c -o CMakeFiles/../ANYKA37EOS.dir/main.c.s

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_add_wifi.c.o: src/CMakeFiles/../ANYKA37EOS.dir/flags.make
src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_add_wifi.c.o: src/layout/layout_add_wifi.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building C object src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_add_wifi.c.o"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_add_wifi.c.o   -c /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_add_wifi.c

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_add_wifi.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37EOS.dir/layout/layout_add_wifi.c.i"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_add_wifi.c > CMakeFiles/../ANYKA37EOS.dir/layout/layout_add_wifi.c.i

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_add_wifi.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37EOS.dir/layout/layout_add_wifi.c.s"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_add_wifi.c -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_add_wifi.c.s

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_cctv.c.o: src/CMakeFiles/../ANYKA37EOS.dir/flags.make
src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_cctv.c.o: src/layout/layout_cctv.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building C object src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_cctv.c.o"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_cctv.c.o   -c /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_cctv.c

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_cctv.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37EOS.dir/layout/layout_cctv.c.i"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_cctv.c > CMakeFiles/../ANYKA37EOS.dir/layout/layout_cctv.c.i

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_cctv.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37EOS.dir/layout/layout_cctv.c.s"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_cctv.c -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_cctv.c.s

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_connect_wifi.c.o: src/CMakeFiles/../ANYKA37EOS.dir/flags.make
src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_connect_wifi.c.o: src/layout/layout_connect_wifi.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building C object src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_connect_wifi.c.o"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_connect_wifi.c.o   -c /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_connect_wifi.c

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_connect_wifi.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37EOS.dir/layout/layout_connect_wifi.c.i"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_connect_wifi.c > CMakeFiles/../ANYKA37EOS.dir/layout/layout_connect_wifi.c.i

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_connect_wifi.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37EOS.dir/layout/layout_connect_wifi.c.s"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_connect_wifi.c -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_connect_wifi.c.s

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_define.c.o: src/CMakeFiles/../ANYKA37EOS.dir/flags.make
src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_define.c.o: src/layout/layout_define.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Building C object src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_define.c.o"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_define.c.o   -c /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_define.c

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_define.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37EOS.dir/layout/layout_define.c.i"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_define.c > CMakeFiles/../ANYKA37EOS.dir/layout/layout_define.c.i

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_define.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37EOS.dir/layout/layout_define.c.s"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_define.c -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_define.c.s

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_home.c.o: src/CMakeFiles/../ANYKA37EOS.dir/flags.make
src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_home.c.o: src/layout/layout_home.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/CMakeFiles --progress-num=$(CMAKE_PROGRESS_6) "Building C object src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_home.c.o"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_home.c.o   -c /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_home.c

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_home.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37EOS.dir/layout/layout_home.c.i"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_home.c > CMakeFiles/../ANYKA37EOS.dir/layout/layout_home.c.i

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_home.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37EOS.dir/layout/layout_home.c.s"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_home.c -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_home.c.s

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_interphone.c.o: src/CMakeFiles/../ANYKA37EOS.dir/flags.make
src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_interphone.c.o: src/layout/layout_interphone.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/CMakeFiles --progress-num=$(CMAKE_PROGRESS_7) "Building C object src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_interphone.c.o"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_interphone.c.o   -c /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_interphone.c

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_interphone.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37EOS.dir/layout/layout_interphone.c.i"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_interphone.c > CMakeFiles/../ANYKA37EOS.dir/layout/layout_interphone.c.i

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_interphone.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37EOS.dir/layout/layout_interphone.c.s"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_interphone.c -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_interphone.c.s

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_keyboard.c.o: src/CMakeFiles/../ANYKA37EOS.dir/flags.make
src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_keyboard.c.o: src/layout/layout_keyboard.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/CMakeFiles --progress-num=$(CMAKE_PROGRESS_8) "Building C object src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_keyboard.c.o"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_keyboard.c.o   -c /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_keyboard.c

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_keyboard.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37EOS.dir/layout/layout_keyboard.c.i"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_keyboard.c > CMakeFiles/../ANYKA37EOS.dir/layout/layout_keyboard.c.i

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_keyboard.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37EOS.dir/layout/layout_keyboard.c.s"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_keyboard.c -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_keyboard.c.s

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_monitor.c.o: src/CMakeFiles/../ANYKA37EOS.dir/flags.make
src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_monitor.c.o: src/layout/layout_monitor.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/CMakeFiles --progress-num=$(CMAKE_PROGRESS_9) "Building C object src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_monitor.c.o"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_monitor.c.o   -c /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_monitor.c

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_monitor.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37EOS.dir/layout/layout_monitor.c.i"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_monitor.c > CMakeFiles/../ANYKA37EOS.dir/layout/layout_monitor.c.i

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_monitor.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37EOS.dir/layout/layout_monitor.c.s"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_monitor.c -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_monitor.c.s

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_photo.c.o: src/CMakeFiles/../ANYKA37EOS.dir/flags.make
src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_photo.c.o: src/layout/layout_photo.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/CMakeFiles --progress-num=$(CMAKE_PROGRESS_10) "Building C object src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_photo.c.o"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_photo.c.o   -c /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_photo.c

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_photo.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37EOS.dir/layout/layout_photo.c.i"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_photo.c > CMakeFiles/../ANYKA37EOS.dir/layout/layout_photo.c.i

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_photo.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37EOS.dir/layout/layout_photo.c.s"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_photo.c -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_photo.c.s

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_playback.c.o: src/CMakeFiles/../ANYKA37EOS.dir/flags.make
src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_playback.c.o: src/layout/layout_playback.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/CMakeFiles --progress-num=$(CMAKE_PROGRESS_11) "Building C object src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_playback.c.o"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_playback.c.o   -c /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_playback.c

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_playback.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37EOS.dir/layout/layout_playback.c.i"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_playback.c > CMakeFiles/../ANYKA37EOS.dir/layout/layout_playback.c.i

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_playback.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37EOS.dir/layout/layout_playback.c.s"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_playback.c -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_playback.c.s

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_set_wifi.c.o: src/CMakeFiles/../ANYKA37EOS.dir/flags.make
src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_set_wifi.c.o: src/layout/layout_set_wifi.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/CMakeFiles --progress-num=$(CMAKE_PROGRESS_12) "Building C object src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_set_wifi.c.o"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_set_wifi.c.o   -c /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_set_wifi.c

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_set_wifi.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37EOS.dir/layout/layout_set_wifi.c.i"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_set_wifi.c > CMakeFiles/../ANYKA37EOS.dir/layout/layout_set_wifi.c.i

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_set_wifi.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37EOS.dir/layout/layout_set_wifi.c.s"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_set_wifi.c -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_set_wifi.c.s

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_setting.c.o: src/CMakeFiles/../ANYKA37EOS.dir/flags.make
src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_setting.c.o: src/layout/layout_setting.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/CMakeFiles --progress-num=$(CMAKE_PROGRESS_13) "Building C object src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_setting.c.o"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_setting.c.o   -c /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_setting.c

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_setting.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37EOS.dir/layout/layout_setting.c.i"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_setting.c > CMakeFiles/../ANYKA37EOS.dir/layout/layout_setting.c.i

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_setting.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37EOS.dir/layout/layout_setting.c.s"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_setting.c -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_setting.c.s

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_standby.c.o: src/CMakeFiles/../ANYKA37EOS.dir/flags.make
src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_standby.c.o: src/layout/layout_standby.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/CMakeFiles --progress-num=$(CMAKE_PROGRESS_14) "Building C object src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_standby.c.o"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_standby.c.o   -c /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_standby.c

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_standby.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37EOS.dir/layout/layout_standby.c.i"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_standby.c > CMakeFiles/../ANYKA37EOS.dir/layout/layout_standby.c.i

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_standby.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37EOS.dir/layout/layout_standby.c.s"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_standby.c -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_standby.c.s

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_video.c.o: src/CMakeFiles/../ANYKA37EOS.dir/flags.make
src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_video.c.o: src/layout/layout_video.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/CMakeFiles --progress-num=$(CMAKE_PROGRESS_15) "Building C object src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_video.c.o"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_video.c.o   -c /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_video.c

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_video.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37EOS.dir/layout/layout_video.c.i"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_video.c > CMakeFiles/../ANYKA37EOS.dir/layout/layout_video.c.i

src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_video.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37EOS.dir/layout/layout_video.c.s"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/layout_video.c -o CMakeFiles/../ANYKA37EOS.dir/layout/layout_video.c.s

src/CMakeFiles/../ANYKA37EOS.dir/layout/user_data.c.o: src/CMakeFiles/../ANYKA37EOS.dir/flags.make
src/CMakeFiles/../ANYKA37EOS.dir/layout/user_data.c.o: src/layout/user_data.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/CMakeFiles --progress-num=$(CMAKE_PROGRESS_16) "Building C object src/CMakeFiles/../ANYKA37EOS.dir/layout/user_data.c.o"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../ANYKA37EOS.dir/layout/user_data.c.o   -c /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/user_data.c

src/CMakeFiles/../ANYKA37EOS.dir/layout/user_data.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../ANYKA37EOS.dir/layout/user_data.c.i"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/user_data.c > CMakeFiles/../ANYKA37EOS.dir/layout/user_data.c.i

src/CMakeFiles/../ANYKA37EOS.dir/layout/user_data.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../ANYKA37EOS.dir/layout/user_data.c.s"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/layout/user_data.c -o CMakeFiles/../ANYKA37EOS.dir/layout/user_data.c.s

# Object files for target ../ANYKA37EOS
__/ANYKA37EOS_OBJECTS = \
"CMakeFiles/../ANYKA37EOS.dir/main.c.o" \
"CMakeFiles/../ANYKA37EOS.dir/layout/layout_add_wifi.c.o" \
"CMakeFiles/../ANYKA37EOS.dir/layout/layout_cctv.c.o" \
"CMakeFiles/../ANYKA37EOS.dir/layout/layout_connect_wifi.c.o" \
"CMakeFiles/../ANYKA37EOS.dir/layout/layout_define.c.o" \
"CMakeFiles/../ANYKA37EOS.dir/layout/layout_home.c.o" \
"CMakeFiles/../ANYKA37EOS.dir/layout/layout_interphone.c.o" \
"CMakeFiles/../ANYKA37EOS.dir/layout/layout_keyboard.c.o" \
"CMakeFiles/../ANYKA37EOS.dir/layout/layout_monitor.c.o" \
"CMakeFiles/../ANYKA37EOS.dir/layout/layout_photo.c.o" \
"CMakeFiles/../ANYKA37EOS.dir/layout/layout_playback.c.o" \
"CMakeFiles/../ANYKA37EOS.dir/layout/layout_set_wifi.c.o" \
"CMakeFiles/../ANYKA37EOS.dir/layout/layout_setting.c.o" \
"CMakeFiles/../ANYKA37EOS.dir/layout/layout_standby.c.o" \
"CMakeFiles/../ANYKA37EOS.dir/layout/layout_video.c.o" \
"CMakeFiles/../ANYKA37EOS.dir/layout/user_data.c.o"

# External object files for target ../ANYKA37EOS
__/ANYKA37EOS_EXTERNAL_OBJECTS =

src/../ANYKA37EOS: src/CMakeFiles/../ANYKA37EOS.dir/main.c.o
src/../ANYKA37EOS: src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_add_wifi.c.o
src/../ANYKA37EOS: src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_cctv.c.o
src/../ANYKA37EOS: src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_connect_wifi.c.o
src/../ANYKA37EOS: src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_define.c.o
src/../ANYKA37EOS: src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_home.c.o
src/../ANYKA37EOS: src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_interphone.c.o
src/../ANYKA37EOS: src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_keyboard.c.o
src/../ANYKA37EOS: src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_monitor.c.o
src/../ANYKA37EOS: src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_photo.c.o
src/../ANYKA37EOS: src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_playback.c.o
src/../ANYKA37EOS: src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_set_wifi.c.o
src/../ANYKA37EOS: src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_setting.c.o
src/../ANYKA37EOS: src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_standby.c.o
src/../ANYKA37EOS: src/CMakeFiles/../ANYKA37EOS.dir/layout/layout_video.c.o
src/../ANYKA37EOS: src/CMakeFiles/../ANYKA37EOS.dir/layout/user_data.c.o
src/../ANYKA37EOS: src/CMakeFiles/../ANYKA37EOS.dir/build.make
src/../ANYKA37EOS: src/lvgl/liblvgl_lib.a
src/../ANYKA37EOS: src/lv_drivers/liblv_drivers_lib.a
src/../ANYKA37EOS: src/api/libleo_api_lib.a
src/../ANYKA37EOS: src/lib/anyka/libplat_tde.so
src/../ANYKA37EOS: src/lib/anyka/libplat_common.so
src/../ANYKA37EOS: src/lib/anyka/libplat_thread.so
src/../ANYKA37EOS: src/lib/anyka/libplat_mem.so
src/../ANYKA37EOS: src/lib/anyka/libplat_osal.so
src/../ANYKA37EOS: src/lib/anyka/libplat_log.so
src/../ANYKA37EOS: src/lib/anyka/libplat_dbg.so
src/../ANYKA37EOS: src/lib/anyka/libmpi_vdec.so
src/../ANYKA37EOS: src/lib/anyka/libakv_decode.so
src/../ANYKA37EOS: src/lib/anyka/libmpi_venc.so
src/../ANYKA37EOS: src/lib/anyka/libakv_encode.so
src/../ANYKA37EOS: src/lib/anyka/libplat_ao.so
src/../ANYKA37EOS: src/lib/anyka/libplat_vqe.so
src/../ANYKA37EOS: src/lib/anyka/libakaudiofilter.so
src/../ANYKA37EOS: src/lib/anyka/libplat_ai.so
src/../ANYKA37EOS: src/lib/anyka/../freetype/libfreetype.a
src/../ANYKA37EOS: src/lib/anyka/../mad/libmad.a
src/../ANYKA37EOS: src/lib/anyka/../tuya/libtuya_ipc.a
src/../ANYKA37EOS: src/lib/anyka/../tuya/libmbedtls.a
src/../ANYKA37EOS: src/lib/anyka/../../api/libleo_api_lib.a
src/../ANYKA37EOS: src/CMakeFiles/../ANYKA37EOS.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/CMakeFiles --progress-num=$(CMAKE_PROGRESS_17) "Linking C executable ../ANYKA37EOS"
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/../ANYKA37EOS.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
src/CMakeFiles/../ANYKA37EOS.dir/build: src/../ANYKA37EOS

.PHONY : src/CMakeFiles/../ANYKA37EOS.dir/build

src/CMakeFiles/../ANYKA37EOS.dir/clean:
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src && $(CMAKE_COMMAND) -P CMakeFiles/../ANYKA37EOS.dir/cmake_clean.cmake
.PHONY : src/CMakeFiles/../ANYKA37EOS.dir/clean

src/CMakeFiles/../ANYKA37EOS.dir/depend:
	cd /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src /mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/ANYKA37EOS.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : src/CMakeFiles/../ANYKA37EOS.dir/depend

