# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# compile C with /opt/arm-anykav500-linux-uclibcgnueabi/usr/bin/arm-anykav500-linux-uclibcgnueabi-gcc
C_FLAGS =  -O3 -Wall -std=gnu11  

C_DEFINES = -DLV_LVGL_H_INCLUDE_SIMPLE

C_INCLUDES = -I/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/./include/anyka -I/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/./include/api -I/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/./include/api/video -I/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/./include/freetype -I/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/./include/libmad -I/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/./include/tuya -I/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/./lvgl -I/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/./lv_drivers -I/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/./layout -I/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/./api/freetype -I/mnt/hgfs/ShareFile/3760E/rui_an/rui_an_indoor/src/./api/network 

