# The set of languages for which implicit dependencies are needed:
set(CMAKE_DEPENDS_LANGUAGES
  "C"
  )
# The set of files for implicit dependencies of each language:
set(CMAKE_DEPENDS_CHECK_C
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/ak_drv_wdt.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/ak_drv_wdt.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/doorbell_upgrade_windows.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/doorbell_upgrade_windows.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/lang_xls.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/lang_xls.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_1_music_list.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_1_music_list.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_1_photo_list.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_1_photo_list.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_1_video_list.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_1_video_list.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_add_data.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_add_data.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_add_wifi.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_add_wifi.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_call.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_call.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_cctv.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_cctv.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_connect_wifi.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_connect_wifi.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_data_list.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_data_list.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_define.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_define.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_device_busy.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_device_busy.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_device_transfer.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_device_transfer.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_event.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_event.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_family_transfer.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_family_transfer.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_file_list.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_file_list.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_home.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_home.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_interphone.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_interphone.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_keyboard.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_keyboard.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_media.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_media.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_media_music.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_media_music.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_media_photo.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_media_photo.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_monitor.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_monitor.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_monitor2.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_monitor2.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_monitor_1.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_monitor_1.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_password_input.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_password_input.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_photo.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_photo.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_playback.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_playback.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_record_list.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_record_list.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_setting.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_setting.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_setting_admin.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_setting_admin.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_setting_camera.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_setting_camera.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_setting_door.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_setting_door.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_setting_info.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_setting_info.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_setting_ipc.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_setting_ipc.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_setting_ring.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_setting_ring.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_setting_scene.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_setting_scene.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_setting_senior.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_setting_senior.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_setting_sys.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_setting_sys.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_setting_wifi.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_setting_wifi.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_standby.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_standby.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_transfer.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_transfer.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_tuya_register.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_tuya_register.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/layout_video.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/layout_video.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/numeric_keypad.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/numeric_keypad.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/tuya_uuid_upgrade.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/tuya_uuid_upgrade.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/upgrade_firmware.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/upgrade_firmware.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/layout/user_data.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/layout/user_data.c.o"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/main.c" "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/ANYKA37E.BIN.dir/main.c.o"
  )
set(CMAKE_C_COMPILER_ID "GNU")

# Preprocessor definitions for this target.
set(CMAKE_TARGET_DEFINITIONS_C
  "ADMIN_CARD_MANAGEMENT"
  "ADMIN_FINGER_MANAGEMENT"
  "ADMIN_PASSW_MANAGEMENT"
  "APP_DEFAULT_PATH=\"/etc/config/\""
  "AUDIO_CONFIG_DEFAULT"
  "DHCP_IPCAMERA"
  "DOORBELL_UPGRADE"
  "HOME_MECHANICAL_KEY"
  "IPC_APP_PID=\"vbnoppvehllkvrrb\""
  "LV_LVGL_H_INCLUDE_SIMPLE"
  "MAILBOX_MODULE_EN"
  "MEIOU_VERSION"
  "MUSIC_FILE_PATH=\"/mnt/tf/music/\""
  "PUBLIC_VERSION"
  "RING_BACK_MODIFY"
  "RING_FILE_PATH=\"/app/app/rings/\""
  "ROM_BIN_PATH=\"/app/app/rom.bin\""
  "ROM_BIN_TEMP_PATH=\"/tmp/rom.bin\""
  "SARADC_DETECT"
  "SDCARD_PARTITION"
  "TTF_FILE_PATH=\"/app/app/sat_leo.ttf\""
  "TTF_XLS_PATH=\"/app/app/language.xls\""
  "TUYA_CACHE_PATH=\"/app/data/tuya_cache/\""
  "TUYA_DATA_PATH=\"/app/data/\""
  "TUYA_KEY_PATH=\"/app/data/tuya_key/\""
  "UNLOCK_HINT_AUDIO"
  "USER_FILE_PATH=\"/app/data/\""
  "WLAN_CHECK_PATH=\"/etc/config/wlan_check.sh\""
  "WPA_SUPPLICANT_PATH=\"/etc/config/wpa_supplicant.conf\""
  "_1COM_VERSION"
  "_GNU_SOURCE"
  "__LITTLE_ENDIAN__"
  )

# The include file search paths:
set(CMAKE_C_TARGET_INCLUDE_PATH
  "src/./include/anyka"
  "src/./include/api"
  "src/./include/api/video"
  "src/./include/freetype"
  "src/./include/libmad"
  "src/./include/tuya"
  "src/./include/g711"
  "src/./include/live555/BasicUsageEnvironment/include"
  "src/./include/live555/groupsock/include"
  "src/./include/live555/liveMedia/include"
  "src/./include/live555/UsageEnvironment/include"
  "src/./lvgl"
  "src/./lv_drivers"
  "src/./lv_qrcode"
  "src/./layout"
  "src/./api/freetype"
  "src/./api/network"
  "src/./api/tcp_network"
  "src/./iniparser/src"
  "src/./tuya_batch_production_sdk/include/libxls"
  "src/./tuya_batch_production_sdk/include/iconv"
  "src/./tuya_batch_production_sdk/xls"
  "src/./onvif/include"
  )

# Targets to which this target links.
set(CMAKE_TARGET_LINKED_INFO_FILES
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/lv_qrcode/CMakeFiles/lv_qrcode_lib.dir/DependInfo.cmake"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/lvgl/CMakeFiles/lvgl_lib.dir/DependInfo.cmake"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/lv_drivers/CMakeFiles/lv_drivers_lib.dir/DependInfo.cmake"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/api/CMakeFiles/leo_api_lib.dir/DependInfo.cmake"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/iniparser/CMakeFiles/iniparser.dir/DependInfo.cmake"
  "/home/leo/workspace/MEIOU/Application/Debug/1COM-Indoor/src/tuya_batch_production_sdk/xls/CMakeFiles/xls.dir/DependInfo.cmake"
  )

# Fortran module output directory.
set(CMAKE_Fortran_TARGET_MODULE_DIR "")
